document.addEventListener('DOMContentLoaded', () => {
  const achievements = document.querySelector('#achievements');
  if (!achievements) return;
  const legacy = document.querySelector('.activity-highlight');
  if (legacy) legacy.remove();

  const section = document.createElement('section');
  section.id = 'activities';
  section.className = 'section activity-records';
  section.innerHTML = `<div class="container"><div class="row align-items-end mb-4"><div class="col-lg-7"><p class="section-no">05 / ACTIVITIES</p><h2 class="section-title">Learning beyond the classroom.</h2></div><div class="col-lg-5"><p class="section-intro ms-lg-auto">Selected professional development and competition records.</p></div></div><div class="row g-4"><div class="col-md-4"><article class="activity-record-card"><div class="activity-record-images two-images"><img src="img/activities/WhatsApp Image 2026-09-19 at 22.53.19.jpeg" alt="International intensive course participants"><img src="img/activities/Muh Aldian Maharani (5)_page-0001.jpg" alt="International intensive course certificate"></div><div class="activity-record-copy"><p>PROFESSIONAL DEVELOPMENT · 2025</p><h3>International Intensive Course on Legal Research &amp; American Legal System</h3><span>Legal research, American legal system, judicial system, and dispute-resolution mechanisms.</span><small>19–21 &amp; 25–28 August 2025</small></div></article></div><div class="col-md-4"><article class="activity-record-card"><div class="activity-record-images two-images"><img src="img/activities/aktivitas 2/WhatsApp Image 2026-09-20 at 02.24.14.jpeg" alt="Moot Court Competition at Universitas Andalas"><img src="img/activities/aktivitas 2/Muh Aldian Maharani (1).jpg" alt="Moot Court Competition certificate"></div><div class="activity-record-copy"><p>MOOT COURT · 2023</p><h3>Moot Court Competition, Mahkamah Konstitusi RI</h3><span>Participated as a delegation at Pekan Konstitusi XIV, held at Faculty of Law, Universitas Andalas, Padang.</span><small>8–11 November 2023</small></div></article></div><div class="col-md-4"><article class="activity-record-card"><div class="activity-record-images two-images"><img src="img/activities/aktivitas 3/WhatsApp Image 2026-09-20 at 02.40.35.jpeg" alt="Internal Debate Competition first place winner"><img src="img/activities/aktivitas 3/WhatsApp Image 2026-09-20 at 02.11.49.jpeg" alt="Conventional Mediation Competition documentation"></div><div class="activity-record-copy"><p>COMPETITION HIGHLIGHTS · 2024–2025</p><h3>Debate &amp; Mediation Competitions</h3><span>1st Place Winner, Internal Debate Competition, Jentera Debate Community (2024).<br><br>3rd Place Winner, Conventional Mediation Competition, Dewan Sengketa Indonesia (2025).</span></div></article></div></div></div>`;
  section.querySelector('.section-title').textContent = 'Professional development & engagements.';
  achievements.after(section);
});
